/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#ifndef IMPORTED_H
#define IMPORTED_H

#ifdef __cplusplus
extern "C" {
#endif

#include "pbtools.h"
#include "types_not_package_name.h"

/**
 * Enum imported.ClientToServer.messages.
 */
enum imported_client_to_server_messages_choice_e {
    imported_client_to_server_messages_choice_none_e = 0,
    imported_client_to_server_messages_choice_foo_e = 1
};

/**
 * Oneof imported.ClientToServer.messages.
 */
struct imported_client_to_server_messages_oneof_t {
    enum imported_client_to_server_messages_choice_e choice;
    union {
        struct types_foo_t foo;
    } value;
};

/**
 * Message imported.ClientToServer.
 */
struct imported_client_to_server_repeated_t {
    int length;
    struct imported_client_to_server_t *items_p;
};

struct imported_client_to_server_t {
    struct pbtools_message_base_t base;
    struct imported_client_to_server_messages_oneof_t messages;
};

/**
 * Enum imported.ServerToClient.messages.
 */
enum imported_server_to_client_messages_choice_e {
    imported_server_to_client_messages_choice_none_e = 0,
    imported_server_to_client_messages_choice_bar_e = 1
};

/**
 * Oneof imported.ServerToClient.messages.
 */
struct imported_server_to_client_messages_oneof_t {
    enum imported_server_to_client_messages_choice_e choice;
    union {
        struct types_bar_t bar;
    } value;
};

/**
 * Message imported.ServerToClient.
 */
struct imported_server_to_client_repeated_t {
    int length;
    struct imported_server_to_client_t *items_p;
};

struct imported_server_to_client_t {
    struct pbtools_message_base_t base;
    struct imported_server_to_client_messages_oneof_t messages;
};

void imported_client_to_server_messages_foo_init(
    struct imported_client_to_server_t *self_p);

/**
 * Encoding and decoding of imported.ClientToServer.
 */
struct imported_client_to_server_t *
imported_client_to_server_new(
    void *workspace_p,
    size_t size);

int imported_client_to_server_encode(
    struct imported_client_to_server_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int imported_client_to_server_decode(
    struct imported_client_to_server_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

void imported_server_to_client_messages_bar_init(
    struct imported_server_to_client_t *self_p);

/**
 * Encoding and decoding of imported.ServerToClient.
 */
struct imported_server_to_client_t *
imported_server_to_client_new(
    void *workspace_p,
    size_t size);

int imported_server_to_client_encode(
    struct imported_server_to_client_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int imported_server_to_client_decode(
    struct imported_server_to_client_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/* Internal functions. Do not use! */

void imported_client_to_server_init(
    struct imported_client_to_server_t *self_p,
    struct pbtools_heap_t *heap_p);

void imported_client_to_server_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct imported_client_to_server_t *self_p);

void imported_client_to_server_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct imported_client_to_server_t *self_p);

void imported_client_to_server_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct imported_client_to_server_repeated_t *repeated_p);

void imported_client_to_server_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct imported_client_to_server_repeated_t *repeated_p);

void imported_server_to_client_init(
    struct imported_server_to_client_t *self_p,
    struct pbtools_heap_t *heap_p);

void imported_server_to_client_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct imported_server_to_client_t *self_p);

void imported_server_to_client_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct imported_server_to_client_t *self_p);

void imported_server_to_client_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct imported_server_to_client_repeated_t *repeated_p);

void imported_server_to_client_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct imported_server_to_client_repeated_t *repeated_p);

#ifdef __cplusplus
}
#endif

#endif
