/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#include <limits.h>
#include "imported.h"

#if CHAR_BIT != 8
#    error "Number of bits in a char must be 8."
#endif

void imported_client_to_server_messages_foo_init(
    struct imported_client_to_server_t *self_p)
{
    self_p->messages.choice = imported_client_to_server_messages_choice_foo_e;
    types_foo_init(
        &self_p->messages.value.foo,
        self_p->base.heap_p);
}

void imported_client_to_server_messages_encode(
    struct pbtools_encoder_t *encoder_p,
    struct imported_client_to_server_messages_oneof_t *self_p)
{
    switch (self_p->choice) {

    case imported_client_to_server_messages_choice_foo_e:
        pbtools_encoder_sub_message_encode_always(
            encoder_p,
            1,
            &self_p->value.foo.base,
            (pbtools_message_encode_inner_t)types_foo_encode_inner);
        break;

    default:
        break;
    }
}

static void imported_client_to_server_messages_foo_decode(
    struct pbtools_decoder_t *decoder_p,
    int wire_type,
    struct imported_client_to_server_t *self_p)
{
    imported_client_to_server_messages_foo_init(self_p);
    pbtools_decoder_sub_message_decode(
        decoder_p,
        wire_type,
        &self_p->messages.value.foo.base,
        (pbtools_message_decode_inner_t)types_foo_decode_inner);
}

void imported_client_to_server_init(
    struct imported_client_to_server_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->messages.choice = 0;
}

void imported_client_to_server_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct imported_client_to_server_t *self_p)
{
    imported_client_to_server_messages_encode(encoder_p, &self_p->messages);
}

void imported_client_to_server_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct imported_client_to_server_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            imported_client_to_server_messages_foo_decode(
                decoder_p,
                wire_type,
                self_p);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void imported_client_to_server_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct imported_client_to_server_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct imported_client_to_server_t),
        (pbtools_message_encode_inner_t)imported_client_to_server_encode_inner);
}

void imported_client_to_server_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct imported_client_to_server_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct imported_client_to_server_t),
        (pbtools_message_init_t)imported_client_to_server_init,
        (pbtools_message_decode_inner_t)imported_client_to_server_decode_inner);
}

struct imported_client_to_server_t *
imported_client_to_server_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct imported_client_to_server_t),
                (pbtools_message_init_t)imported_client_to_server_init));
}

int imported_client_to_server_encode(
    struct imported_client_to_server_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)imported_client_to_server_encode_inner));
}

int imported_client_to_server_decode(
    struct imported_client_to_server_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)imported_client_to_server_decode_inner));
}

void imported_server_to_client_messages_bar_init(
    struct imported_server_to_client_t *self_p)
{
    self_p->messages.choice = imported_server_to_client_messages_choice_bar_e;
    types_bar_init(
        &self_p->messages.value.bar,
        self_p->base.heap_p);
}

void imported_server_to_client_messages_encode(
    struct pbtools_encoder_t *encoder_p,
    struct imported_server_to_client_messages_oneof_t *self_p)
{
    switch (self_p->choice) {

    case imported_server_to_client_messages_choice_bar_e:
        pbtools_encoder_sub_message_encode_always(
            encoder_p,
            1,
            &self_p->value.bar.base,
            (pbtools_message_encode_inner_t)types_bar_encode_inner);
        break;

    default:
        break;
    }
}

static void imported_server_to_client_messages_bar_decode(
    struct pbtools_decoder_t *decoder_p,
    int wire_type,
    struct imported_server_to_client_t *self_p)
{
    imported_server_to_client_messages_bar_init(self_p);
    pbtools_decoder_sub_message_decode(
        decoder_p,
        wire_type,
        &self_p->messages.value.bar.base,
        (pbtools_message_decode_inner_t)types_bar_decode_inner);
}

void imported_server_to_client_init(
    struct imported_server_to_client_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->messages.choice = 0;
}

void imported_server_to_client_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct imported_server_to_client_t *self_p)
{
    imported_server_to_client_messages_encode(encoder_p, &self_p->messages);
}

void imported_server_to_client_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct imported_server_to_client_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            imported_server_to_client_messages_bar_decode(
                decoder_p,
                wire_type,
                self_p);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void imported_server_to_client_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct imported_server_to_client_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct imported_server_to_client_t),
        (pbtools_message_encode_inner_t)imported_server_to_client_encode_inner);
}

void imported_server_to_client_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct imported_server_to_client_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct imported_server_to_client_t),
        (pbtools_message_init_t)imported_server_to_client_init,
        (pbtools_message_decode_inner_t)imported_server_to_client_decode_inner);
}

struct imported_server_to_client_t *
imported_server_to_client_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct imported_server_to_client_t),
                (pbtools_message_init_t)imported_server_to_client_init));
}

int imported_server_to_client_encode(
    struct imported_server_to_client_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)imported_server_to_client_encode_inner));
}

int imported_server_to_client_decode(
    struct imported_server_to_client_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)imported_server_to_client_decode_inner));
}
