/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#ifndef MY_PROTOCOL_H
#define MY_PROTOCOL_H

#ifdef __cplusplus
extern "C" {
#endif

#include "pbtools.h"

/**
 * Message my_protocol.FooReq.
 */
struct my_protocol_foo_req_repeated_t {
    int length;
    struct my_protocol_foo_req_t *items_p;
};

struct my_protocol_foo_req_t {
    struct pbtools_message_base_t base;
};

/**
 * Message my_protocol.BarInd.
 */
struct my_protocol_bar_ind_repeated_t {
    int length;
    struct my_protocol_bar_ind_t *items_p;
};

struct my_protocol_bar_ind_t {
    struct pbtools_message_base_t base;
};

/**
 * Message my_protocol.FieRsp.
 */
struct my_protocol_fie_rsp_repeated_t {
    int length;
    struct my_protocol_fie_rsp_t *items_p;
};

struct my_protocol_fie_rsp_t {
    struct pbtools_message_base_t base;
};

/**
 * Enum my_protocol.ClientToServer.messages.
 */
enum my_protocol_client_to_server_messages_choice_e {
    my_protocol_client_to_server_messages_choice_none_e = 0,
    my_protocol_client_to_server_messages_choice_foo_req_e = 1,
    my_protocol_client_to_server_messages_choice_bar_ind_e = 2,
    my_protocol_client_to_server_messages_choice_fie_rsp_e = 3
};

/**
 * Oneof my_protocol.ClientToServer.messages.
 */
struct my_protocol_client_to_server_messages_oneof_t {
    enum my_protocol_client_to_server_messages_choice_e choice;
    union {
        struct my_protocol_foo_req_t foo_req;
        struct my_protocol_bar_ind_t bar_ind;
        struct my_protocol_fie_rsp_t fie_rsp;
    } value;
};

/**
 * Message my_protocol.ClientToServer.
 */
struct my_protocol_client_to_server_repeated_t {
    int length;
    struct my_protocol_client_to_server_t *items_p;
};

struct my_protocol_client_to_server_t {
    struct pbtools_message_base_t base;
    struct my_protocol_client_to_server_messages_oneof_t messages;
};

/**
 * Message my_protocol.FooRsp.
 */
struct my_protocol_foo_rsp_repeated_t {
    int length;
    struct my_protocol_foo_rsp_t *items_p;
};

struct my_protocol_foo_rsp_t {
    struct pbtools_message_base_t base;
};

/**
 * Message my_protocol.FieReq.
 */
struct my_protocol_fie_req_repeated_t {
    int length;
    struct my_protocol_fie_req_t *items_p;
};

struct my_protocol_fie_req_t {
    struct pbtools_message_base_t base;
};

/**
 * Enum my_protocol.ServerToClient.messages.
 */
enum my_protocol_server_to_client_messages_choice_e {
    my_protocol_server_to_client_messages_choice_none_e = 0,
    my_protocol_server_to_client_messages_choice_foo_rsp_e = 1,
    my_protocol_server_to_client_messages_choice_fie_req_e = 2
};

/**
 * Oneof my_protocol.ServerToClient.messages.
 */
struct my_protocol_server_to_client_messages_oneof_t {
    enum my_protocol_server_to_client_messages_choice_e choice;
    union {
        struct my_protocol_foo_rsp_t foo_rsp;
        struct my_protocol_fie_req_t fie_req;
    } value;
};

/**
 * Message my_protocol.ServerToClient.
 */
struct my_protocol_server_to_client_repeated_t {
    int length;
    struct my_protocol_server_to_client_t *items_p;
};

struct my_protocol_server_to_client_t {
    struct pbtools_message_base_t base;
    struct my_protocol_server_to_client_messages_oneof_t messages;
};

/**
 * Encoding and decoding of my_protocol.FooReq.
 */
struct my_protocol_foo_req_t *
my_protocol_foo_req_new(
    void *workspace_p,
    size_t size);

int my_protocol_foo_req_encode(
    struct my_protocol_foo_req_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int my_protocol_foo_req_decode(
    struct my_protocol_foo_req_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/**
 * Encoding and decoding of my_protocol.BarInd.
 */
struct my_protocol_bar_ind_t *
my_protocol_bar_ind_new(
    void *workspace_p,
    size_t size);

int my_protocol_bar_ind_encode(
    struct my_protocol_bar_ind_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int my_protocol_bar_ind_decode(
    struct my_protocol_bar_ind_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/**
 * Encoding and decoding of my_protocol.FieRsp.
 */
struct my_protocol_fie_rsp_t *
my_protocol_fie_rsp_new(
    void *workspace_p,
    size_t size);

int my_protocol_fie_rsp_encode(
    struct my_protocol_fie_rsp_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int my_protocol_fie_rsp_decode(
    struct my_protocol_fie_rsp_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

void my_protocol_client_to_server_messages_foo_req_init(
    struct my_protocol_client_to_server_t *self_p);

void my_protocol_client_to_server_messages_bar_ind_init(
    struct my_protocol_client_to_server_t *self_p);

void my_protocol_client_to_server_messages_fie_rsp_init(
    struct my_protocol_client_to_server_t *self_p);

/**
 * Encoding and decoding of my_protocol.ClientToServer.
 */
struct my_protocol_client_to_server_t *
my_protocol_client_to_server_new(
    void *workspace_p,
    size_t size);

int my_protocol_client_to_server_encode(
    struct my_protocol_client_to_server_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int my_protocol_client_to_server_decode(
    struct my_protocol_client_to_server_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/**
 * Encoding and decoding of my_protocol.FooRsp.
 */
struct my_protocol_foo_rsp_t *
my_protocol_foo_rsp_new(
    void *workspace_p,
    size_t size);

int my_protocol_foo_rsp_encode(
    struct my_protocol_foo_rsp_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int my_protocol_foo_rsp_decode(
    struct my_protocol_foo_rsp_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/**
 * Encoding and decoding of my_protocol.FieReq.
 */
struct my_protocol_fie_req_t *
my_protocol_fie_req_new(
    void *workspace_p,
    size_t size);

int my_protocol_fie_req_encode(
    struct my_protocol_fie_req_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int my_protocol_fie_req_decode(
    struct my_protocol_fie_req_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

void my_protocol_server_to_client_messages_foo_rsp_init(
    struct my_protocol_server_to_client_t *self_p);

void my_protocol_server_to_client_messages_fie_req_init(
    struct my_protocol_server_to_client_t *self_p);

/**
 * Encoding and decoding of my_protocol.ServerToClient.
 */
struct my_protocol_server_to_client_t *
my_protocol_server_to_client_new(
    void *workspace_p,
    size_t size);

int my_protocol_server_to_client_encode(
    struct my_protocol_server_to_client_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int my_protocol_server_to_client_decode(
    struct my_protocol_server_to_client_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/* Internal functions. Do not use! */

void my_protocol_foo_req_init(
    struct my_protocol_foo_req_t *self_p,
    struct pbtools_heap_t *heap_p);

void my_protocol_foo_req_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct my_protocol_foo_req_t *self_p);

void my_protocol_foo_req_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct my_protocol_foo_req_t *self_p);

void my_protocol_foo_req_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct my_protocol_foo_req_repeated_t *repeated_p);

void my_protocol_foo_req_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct my_protocol_foo_req_repeated_t *repeated_p);

void my_protocol_bar_ind_init(
    struct my_protocol_bar_ind_t *self_p,
    struct pbtools_heap_t *heap_p);

void my_protocol_bar_ind_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct my_protocol_bar_ind_t *self_p);

void my_protocol_bar_ind_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct my_protocol_bar_ind_t *self_p);

void my_protocol_bar_ind_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct my_protocol_bar_ind_repeated_t *repeated_p);

void my_protocol_bar_ind_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct my_protocol_bar_ind_repeated_t *repeated_p);

void my_protocol_fie_rsp_init(
    struct my_protocol_fie_rsp_t *self_p,
    struct pbtools_heap_t *heap_p);

void my_protocol_fie_rsp_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct my_protocol_fie_rsp_t *self_p);

void my_protocol_fie_rsp_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct my_protocol_fie_rsp_t *self_p);

void my_protocol_fie_rsp_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct my_protocol_fie_rsp_repeated_t *repeated_p);

void my_protocol_fie_rsp_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct my_protocol_fie_rsp_repeated_t *repeated_p);

void my_protocol_client_to_server_init(
    struct my_protocol_client_to_server_t *self_p,
    struct pbtools_heap_t *heap_p);

void my_protocol_client_to_server_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct my_protocol_client_to_server_t *self_p);

void my_protocol_client_to_server_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct my_protocol_client_to_server_t *self_p);

void my_protocol_client_to_server_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct my_protocol_client_to_server_repeated_t *repeated_p);

void my_protocol_client_to_server_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct my_protocol_client_to_server_repeated_t *repeated_p);

void my_protocol_foo_rsp_init(
    struct my_protocol_foo_rsp_t *self_p,
    struct pbtools_heap_t *heap_p);

void my_protocol_foo_rsp_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct my_protocol_foo_rsp_t *self_p);

void my_protocol_foo_rsp_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct my_protocol_foo_rsp_t *self_p);

void my_protocol_foo_rsp_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct my_protocol_foo_rsp_repeated_t *repeated_p);

void my_protocol_foo_rsp_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct my_protocol_foo_rsp_repeated_t *repeated_p);

void my_protocol_fie_req_init(
    struct my_protocol_fie_req_t *self_p,
    struct pbtools_heap_t *heap_p);

void my_protocol_fie_req_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct my_protocol_fie_req_t *self_p);

void my_protocol_fie_req_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct my_protocol_fie_req_t *self_p);

void my_protocol_fie_req_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct my_protocol_fie_req_repeated_t *repeated_p);

void my_protocol_fie_req_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct my_protocol_fie_req_repeated_t *repeated_p);

void my_protocol_server_to_client_init(
    struct my_protocol_server_to_client_t *self_p,
    struct pbtools_heap_t *heap_p);

void my_protocol_server_to_client_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct my_protocol_server_to_client_t *self_p);

void my_protocol_server_to_client_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct my_protocol_server_to_client_t *self_p);

void my_protocol_server_to_client_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct my_protocol_server_to_client_repeated_t *repeated_p);

void my_protocol_server_to_client_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct my_protocol_server_to_client_repeated_t *repeated_p);

#ifdef __cplusplus
}
#endif

#endif
