/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2020, Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/* This file was generated by Messi. */

#include "messi.h"
#include "chat_server.h"

static void on_connected_default(struct chat_server_t *self_p,
                                 struct chat_server_client_t *client_p)
{
    (void)self_p;
    (void)client_p;
}

static void on_disconnected_default(struct chat_server_t *self_p,
                                    struct chat_server_client_t *client_p)
{
    (void)self_p;
    (void)client_p;
}

static void on_client_connected()
{
}

static void on_client_disconnected()
{
}

static void on_client_input(struct async_stcp_server_client_t *client_p)
{
    (void)client_p;
}

void chat_server_new_output_message(struct chat_server_t *self_p)
{
    self_p->output.message_p = chat_server_to_client_new(
        &self_p->output.workspace.buf_p[0],
        self_p->output.workspace.size);
}

static void on_connect_req_default(
    struct chat_server_t *self_p,
    struct chat_server_client_t *client_p,
    struct chat_connect_req_t *message_p)
{
    (void)self_p;
    (void)client_p;
    (void)message_p;
}
static void on_message_ind_default(
    struct chat_server_t *self_p,
    struct chat_server_client_t *client_p,
    struct chat_message_ind_t *message_p)
{
    (void)self_p;
    (void)client_p;
    (void)message_p;
}

int chat_server_init(
    struct chat_server_t *self_p,
    const char *server_uri_p,
    struct chat_server_client_t *clients_p,
    int clients_max,
    uint8_t *clients_input_bufs_p,
    size_t client_input_size,
    uint8_t *workspace_in_buf_p,
    size_t workspace_in_size,
    uint8_t *workspace_out_buf_p,
    size_t workspace_out_size,
    chat_server_on_client_connected_t on_connected,
    chat_server_on_client_disconnected_t on_disconnected,
    chat_server_on_connect_req_t on_connect_req,
    chat_server_on_message_ind_t on_message_ind,
    struct async_t *async_p)
{
    int res;
    int i;
    
    if (on_connect_req == NULL) {
        on_connect_req = on_connect_req_default;
    }

    if (on_message_ind == NULL) {
        on_message_ind = on_message_ind_default;
    }

    if (on_connected == NULL) {
        on_connected = on_connected_default;
    }

    if (on_disconnected == NULL) {
        on_disconnected = on_disconnected_default;
    }

    res = messi_parse_tcp_uri(server_uri_p,
                              &self_p->server.address[0],
                              sizeof(self_p->server.address),
                              &self_p->server.port);

    if (res != 0) {
        return (res);
    }

    self_p->on_connect_req = on_connect_req;
    self_p->on_message_ind = on_message_ind;
    (void)workspace_in_buf_p;
    (void)workspace_in_size;
    self_p->output.workspace.buf_p = workspace_out_buf_p;
    self_p->output.workspace.size = workspace_out_size;
    self_p->async_p = async_p;
    async_stcp_server_init(&self_p->stcp,
                           &self_p->server.address[0],
                           self_p->server.port,
                           NULL,
                           on_client_connected,
                           on_client_disconnected,
                           on_client_input,
                           async_p);

    for (i = 0; i < clients_max; i++) {
        clients_p[i].input.data.buf_p = &clients_input_bufs_p[i * client_input_size];
        clients_p[i].input.data.size = client_input_size;
        async_stcp_server_add_client(&self_p->stcp, &clients_p[i].stcp);
    }
    
    return (0);
}

void chat_server_start(struct chat_server_t *self_p)
{
    async_stcp_server_start(&self_p->stcp);
}

void chat_server_stop(struct chat_server_t *self_p)
{
    async_stcp_server_stop(&self_p->stcp);
}

void chat_server_send(struct chat_server_t *self_p,
                      struct chat_server_client_t *client_p)
{
    int res;
    struct messi_header_t *header_p;

    res = chat_server_to_client_encode(
        self_p->output.message_p,
        &self_p->output.message.buf_p[sizeof(*header_p)],
        self_p->output.message.size - sizeof(*header_p));

    if (res < 0) {
        return;
    }

    header_p = (struct messi_header_t *)&self_p->output.message.buf_p[0];
    messi_header_create(header_p, MESSI_MESSAGE_TYPE_SERVER_TO_CLIENT_USER, res);
    async_stcp_server_client_write(&client_p->stcp,
                                   &self_p->output.message.buf_p[0],
                                   res + sizeof(*header_p));
}

struct chat_connect_rsp_t *chat_server_init_connect_rsp(
    struct chat_server_t *self_p)
{
    chat_server_new_output_message(self_p);
    chat_server_to_client_messages_connect_rsp_init(self_p->output.message_p);

    return (&self_p->output.message_p->messages.value.connect_rsp);
}

struct chat_message_ind_t *chat_server_init_message_ind(
    struct chat_server_t *self_p)
{
    chat_server_new_output_message(self_p);
    chat_server_to_client_messages_message_ind_init(self_p->output.message_p);

    return (&self_p->output.message_p->messages.value.message_ind);
}

